```yml
#配置 数据库连接
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/borrowing
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

#   配置druid

druid:
  aop-patterns: com.wjg.bootweb.*  #监控该路径下的所有配置 SpringBean
  filters: stat,wall  #底层开启功能，stat（sql监控），wall（防火墙）

  stat-view-servlet:  #配置监控页面功能
    enabled: true  #开启功能
    url-pattern: "/druid/*"
    #登录账号和密码
    login-username: admin
    login-password: admin
    resetEnable: false  #重置按钮

  web-stat-filter:  # 监控web
    enabled: true
    urlPattern: /*
    exclusions: '*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*'

  filter:
    stat:    # 对上面filters里面的stat的详细配置
      enabled: true
      slow-sql-millis: 1000
      logSlowSql: true
    wall:
      enabled: true
      config:
        drop-table-allow: false
        
config:
  name: "xiaowuwuwuwuwuwuwu abbb"
        
```

